{"name":"invalidLog","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"java.lang.RuntimeException: File src\\main\\resouces\\DataProvider\\NegativeLoginTestinvalidLog.csv was not found.\n[Ljava.lang.StackTraceElement;@6f53b8a","trace":"java.lang.RuntimeException: java.lang.RuntimeException: File src\\main\\resouces\\DataProvider\\NegativeLoginTestinvalidLog.csv was not found.\n[Ljava.lang.StackTraceElement;@6f53b8a\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)\r\n\tat org.testng.internal.Parameters.handleParameters(Parameters.java:706)\r\n\tat org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)\r\n\tat org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:924)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:648)\r\n\tat org.testng.TestRunner.run(TestRunner.java:505)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:455)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:364)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1137)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1049)\r\n\tat org.testng.TestNG.run(TestNG.java:1017)\r\n\tat org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)\r\n\tat org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)\r\nCaused by: java.lang.RuntimeException: File src\\main\\resouces\\DataProvider\\NegativeLoginTestinvalidLog.csv was not found.\n[Ljava.lang.StackTraceElement;@6f53b8a\r\n\tat Utils.CsvDataProviders.csvReader(CsvDataProviders.java:36)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)\r\n\t... 21 more\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1612301482336,"stop":1612301482369,"uuid":"c0d12441-575d-4933-ad5c-7bdac9e8098e","historyId":"c2c9440775732e4d72cf3fd41fdddfe9","fullName":"TestCases.NegativeLoginTest.invalidLog","labels":[{"name":"package","value":"TestCases.NegativeLoginTest"},{"name":"testClass","value":"TestCases.NegativeLoginTest"},{"name":"testMethod","value":"invalidLog"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"AdvanceSeleniumTraining"},{"name":"subSuite","value":"TestCases.NegativeLoginTest"},{"name":"host","value":"DESKTOP-AQB3208"},{"name":"thread","value":"11576@DESKTOP-AQB3208.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[]}